### ISSUE TITLE
Text is being cutted when pasting.

### ISSUE THREAD

**Issue by ptykamikaze** [php-school/cli-menu#165] opened 2018-08-03 03:10 UTC
Hello! I'm trying to use your cli which is very nice tool but I'm having a problem. When I'm pasting a text, it is being reduced. For example if I paste CSLAD00000334, the cli return CSLAD0000033. The weird thing is that if I press space, the last character appears. Can anyone help me with this issue?

**Comment by Lynesth** [comment] 2018-08-03 03:13
Hey there,

Where exactly are you pasting the text ? Is it in an input ? If so, which one ?
Are you experiencing the same issue if you try pasting something shorter ?

**Comment by ptykamikaze** [comment] 2018-08-03 14:57
Hello. I'm using this method to generate an input

```
        $result = $menu->askText()
                    ->setPromptText('Enter the number)
                    ->setValidationFailedText('Invalid number')
                    ->setPlaceholderText('#')
                    ->ask();
```
Temporally, I have modified this file "NonCanonicalReader.php", line 64, to allow up to 30 characters and for the moment it is working...

`$char = $this->terminal->read(30);`

Thanks for your quick response...

**Comment by AydinHassan** [comment] 2018-09-04 10:31
hey @ptykamikaze sorry for the very late reply. This is an interesting problem and I'm not sure what the solution should be. I never considered pasting in to the field when building this. I think the best way to solve this might be to PR a failing test case highlighting the issue and then we can discuss and figure out a solution.

While your solution does work for your use case, any pasted string over 30 chars would still result in trimming.

**Comment by tbannister** [comment] 2023-01-06 22:11
I've experimented a little further with this, and this is interesting, the processing bug only appears on the second or later block pasted text according to the length specified in the NonCanonicalReader.php file in the terminal library.  If you paste a three character string, it always works, but if you paste 5 or longer and it's not divisible by 4 you get one of the buggy interactions.  If you increase the size of the read call in NonCanonicalReader.php the string now has to be divisible by the new value to work.

**Comment by tbannister** [comment] 2023-01-06 23:04
I think the issue is with the fread call in ResourceInputStream.php.  It looks like fread is blocking on the final call because not enough data is ready to continue.  If there are between 1 and 3 leftover characters, it blocks until new input triggers it to run again.

**Comment by AydinHassan** [comment] 2023-01-07 11:45
Yeah I am not sure how to solve this, we need to read more than 1 char because from what I remember some control sequences come throw as more than one char.

**Comment by tbannister** [comment] 2023-01-09 15:52
I've been poking around the stream reading documentation for PHP, and it seems like there are three possible solutions:

1. Boost the read size to a very large number (8192, for example) so that any legitimately sized input should be read in the first fread.
2. Use fgets to get input one line at a time for inputs.
3. Turn off blocking on stdin when data is read, and turn it back on when no more data is left.

The third option seems simplest, most scalable, and in testing fixes the problem.  It requires a small change to ResourceInputStream.php in the terminal library.

**Comment by AydinHassan** [comment] 2023-01-09 16:00
@tbannister nice investigation, go for it, hopefully the test suite should highlight any issues :)

**Comment by tbannister** [comment] 2023-01-09 16:08
A pull request has been submitted to terminal.

**Comment by tbannister** [comment] 2023-01-11 19:38
After using the patched code for a bit, I discovered that I had unintentionally created a side effect where the blocking status of the input stream could be changed.  I've submitted an updated pull request with a new commit that saves the initial blocking status and restores that status when the stream object is destroyed.

**Comment by AydinHassan** [comment] 2023-01-11 19:44
I've merged it 🙂

**Closed** 2023-11-05 12:47 UTC
