### ISSUE TITLE
Output Text

### ISSUE THREAD

**Issue by JohnatanT** [php-school/cli-menu#101] opened 2018-05-04 15:06 UTC
Hi, can you customize the text that will appear when choosing an item? Same as Flash Dialogue, but I do not want a "modal".

**Comment by JohnatanT** [comment] 2018-05-04 15:49
Is there any function like this? (setText)

->addItem('First Item', $itemCallable)->setText("My Text")

**Comment by Lynesth** [comment] 2018-05-05 15:16
Hi @JohnatanT,

What do you mean by "that will appear when choosing an item" ? Where do you want your "My Text" to appear exactly ?

**Comment by JohnatanT** [comment] 2018-05-06 16:41
In the terminal when we choose an item it shows the text of the selected item, but I wanted it to show a text that I want for each item and not the name of the item.

**Comment by JohnatanT** [comment] 2018-05-06 16:43
For example:
If I have an item called "First Item" and select it, it will appear in the "First Item" terminal. But I want another text and not the item name.

**Comment by AydinHassan** [comment] 2018-05-06 20:09
Could you maybe explain your use case? Why is the text attribute not enough? That is what is was designed for - there is no "name" attribute. It is just the text to be displayed on the menu. What are you using the text "First Item" for if it is not the text to be displayed on the menu?

**Comment by Lynesth** [comment] 2018-05-07 00:02
I guess you are using the example from the docs. If so, then it looks like this:

```php
$itemCallable = function (CliMenu $menu) {
    echo $menu->getSelectedItem()->getText();
};

...
->addItem('First Item', $itemCallable)
...
```

When you select 'First Item' (I mean when you go over it and then press ENTER), the script will invoque the second argument of your `addItem` call ($itemCallable in this case), which currently prints the the selected item text.

You just have to modify the content of the function to return something else.

For example:

```php
$itemCallable = function (CliMenu $menu) {
    echo '4';
};

...
->addItem('What is 2+2 ?', $itemCallable)
...
```
This would print 4.

If that wasn't what you meant, then disregard my comment.

**Comment by JohnatanT** [comment] 2018-05-07 21:03
Considering his example:
-> addItem ('What is 2 + 2?', $ itemCallable)
What if I want multiple items with custom text?
-> addItem ('What is 2 + 2?', $ itemCallable)
-> addItem ('What is 3 + 3?', $ itemCallable)
-> addItem ('What is 4 + 4?', $ itemCallable)
How would you have a different answer for each one?

**Comment by Lynesth** [comment] 2018-05-08 01:12
Ok so as I said in my previous answer, the second argument is the function that is invoked when you select the item. You just need to have a different function for each of them:

```php
// You can define them beforehand
$prints4 = function(CliMenu $menu) {
    echo '4';
}
$prints6 = function(CliMenu $menu) {
    echo '6';
}

...
->addItem('What is 2 + 2?', $print4)
->addItem('What is 3 + 3?', $print6)
// Or you can use anonymous functions
->addItem('What is 4 + 4?', function(CliMenu $menu) {
    echo '8';
})


// Now let's say your retrieving a bunch of data (some books for example)
// from your database and you want to add them to your menu.
// Each rows consists of a title, a price, a number of pages and the author
$books = /* Your awesome query to get them from your database */;

// Then to add them to the menu you could do something like this
$menuBuilder = (new CliMenuBuilder)
    ->setWidth(200)
    ->...
foreach ($books as $book) {
    $menuBuilder->addItem($book->title, function(CliMenu $menu) use ($book) {
        echo 'Title: ' . $book->title;
        echo 'Author: ' . $book->author;
        echo 'Number of pages: ' . $book->pages;
        echo 'Price: ' . $book->price;
    });
}
$menu = $menuBuilder->build();
```

I hope this helps you. Let me know if you have trouble understanding it or if you have other questions.

**Comment by AydinHassan** [comment] 2018-05-08 07:42
Ok I'm closing this now - thanks for the examples @Lynesth and I hope that clears it up. @JohnatanT feel free to drop in the slack channel if you need some more assistance :)

**Closed by AydinHassan** 2018-05-08 07:42 UTC
