### ISSUE TITLE
askText() requires two presses of enter and cuts the line (during copy/paste)

### ISSUE THREAD

**Issue by zhdanov** [php-school/cli-menu#264] opened 2022-10-30 09:22 UTC
Hello, here is an example:

```php
<?php
require __DIR__.'/vendor/autoload.php';

use PhpSchool\CliMenu\Builder\CliMenuBuilder;
use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\MenuStyle;

$builder = new CliMenuBuilder;

$itemCallable = function ($menu) {
    $style = (new MenuStyle())->setBg('black')->setFg('white');

    $result = $menu->askText($style)
        ->setPromptText('Title')
        ->setPlaceholderText('Placeholder')
        ->ask();

    echo $result->fetch();
};

$builder->addSubMenu('Item 1', function (CliMenuBuilder $b) use ($itemCallable) {
    $b->setTitle('Menu > Item 1');

    $b->addItem('Sub item', function (CliMenu $menu) use ($itemCallable) {
        $itemCallable($menu);
    });
});

$menu = $builder->build();

$menu->open();
```

Copy and paste into dialog: "Lorem ipsum dolor sit amet".
```
result:   Lorem ipsum dolor sit am
expected: Lorem ipsum dolor sit amet
```

**Comment by AydinHassan** [comment] 2022-10-31 09:38
Yeah this is a bug, seems like a duplicate of https://github.com/php-school/cli-menu/issues/165#issuecomment-418318941. Please feel free to continue the discussion there :)

**Closed** 2022-10-31 09:38 UTC
